stages:
  - install
  - lint
  - test
  - build

variables:
  NODE_ENV: 'development'

before_script:
  - npm install

install_dependencies:
  stage: install
  script:
    - npm install

lint:
  stage: lint
  script:
    - npm run lint # Ensure you have a lint script in package.json

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build # Ensure you have a build script in package.json
  artifacts:
    paths:
      - dist/ # Adjust if your build outputs to a different directory
